server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      force: true
      charset: utf-8
spring:
  application:
    name: mcp-client

  ai:
    dashscope:
      api-key: sk-4246e826d02342b4bb713f68a1ff7b6f
    memory:
      redis:
        host: 192.168.174.128
        port: 6379
    mcp:
      client:
        type: async
        request-timeout: 60s
        toolcallback:
          enabled: true
        stdio:
          servers-configuration: classpath:/mcp-server.json5
        # sse:
        #   connections:
        #     mcp-server1:
        #       url: http://localhost:8014
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
    com.vanpine.mcpclient: DEBUG




